on: push

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:FireWorks-Studios/ScratchGO.git"
          source_branch: "main"
          destination_repo: "weitude/sync-ScratchGO"
          destination_branch: "main"